services:
  - type: web
    name: wacanan
    runtime: docker
    repo: https://github.com/WilsonCc7/wacanan
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_NAME
        value: Wacanan
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://wacanan.wilsb.me
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: COVERS_BUCKET
        value: wacanan-cover
      - key: COVERS_DEFAULT_REGION
        value: ap-southeast-1
      - key: COVERS_ENDPOINT
        value: https://br-fancy-haze-azrtiv36.storage.c-3.ap-southeast-1.aws.neon.tech
      - key: COVERS_URL
        value: https://br-fancy-haze-azrtiv36.storage.c-3.ap-southeast-1.aws.neon.tech/wacanan-cover
      - key: COVERS_USE_PATH_STYLE_ENDPOINT
        value: true
      - key: COVERS_ACCESS_KEY_ID
        sync: false
      - key: COVERS_SECRET_ACCESS_KEY
        sync: false
